### ISSUE TITLE
Support min / max config options

### ISSUE THREAD

**Issue by simonsheridan** [bcherny/format-as-currency#1]
I was thinking something like

```
<input type="text" name="input" ng-model="amount" min="0.01" max="{{modelVal}}" format-as-currency>
```

I will be happy to make this change, and possibly others, and submit a PR as long as you (the maintainer) are open to PR submissions.

Awesome work, this is a very handy directive

**Comment by bcherny** [comment]
thanks for the feedback!

min/max are a separate concern from what format-as-currency does, and i would use a separate directive to validate those bounds. maybe something like:

``` js
angular.directive('minMax', function(){
  return {
    restrict: 'A',
    require: 'ngModel',
    scope: false,
    link: function (scope, _, attrs, ngModel) {

      var min = scope.$eval(attrs.min)
      var max = scope.$eval(attrs.max)

      ngModel.$validators.minMax = function (modelValue) {
        return modelValue >= min && modelValue <= max
      }

    }
  }
})
```

**Comment by simonsheridan** [comment]
thanks!
