### ISSUE TITLE
Moving the cursor to the dollar sign and typing non-numeric characters

### ISSUE THREAD

**Issue by simonsheridan** [bcherny/format-as-currency#2]
If you move the cursor (using arrows or click) to either side of the `$` and type non-numeric characters, the characters will show up, whereas in any other place they will not show up.

@bcherny if you agree that this is an issue I will take a look and see if i can submit a PR

**Comment by bcherny** [comment]
duplicate of https://github.com/bcherny/format-as-currency/issues/3
