### ISSUE TITLE
Doesn't accept currency filter arguments

### ISSUE THREAD

**Issue by danielr18** [bcherny/format-as-currency#24]
Refer to: https://docs.angularjs.org/api/ng/filter/currency.

This would allow to change the currency symbol or fraction size quickly from a directive attribute,

**Comment by bcherny** [comment]
What is the custom format you're trying to use?

**Comment by danielr18** [comment]
I've been using it for putting a blank currency symbol and a negative as current symbol.

**Comment by bcherny** [comment]
Can you do

``` js
  .filter('myFilter', function ($filter) {
    return function (value) {
      return $filter('currency')(value, '')
    }
  })
```

**Comment by danielr18** [comment]
Yes, I think that would also work

**Comment by bcherny** [comment]
Great - if you can use this more generic solution, I'll close your PR.

**Comment by danielr18** [comment]
If you would like, I think changing `return '¥' + value` to `return $filter('currency')(value, '¥')` would be more helpful in the ReadMe.

**Comment by bcherny** [comment]
@danielr18 Added docs to readme
